### ISSUE TITLE
Report page update

### ISSUE THREAD

**Issue by mvanspringel** [Intracto/SecretSanta#268]
The first thing that should happen is that the page actually loads again. It takes too long right now and even timeouts.

## todo's

- [ ] remove all queries from the report page and load the data via AJAX
- [ ] move reporting queries and services to a separate subdomain, do not use the existing Entities
- [ ] do research to check if AMP can bring any value on this page
- [ ] add new stats about bounced / received / opened / confirmed statuses
