### ISSUE TITLE
[RFC] Replace gulp setup with simplified Symfony encore

### ISSUE THREAD

**Issue by acrobat** [Intracto/SecretSanta#320]
Symfony recently announced [encore ](https://symfony.com/blog/introducing-webpack-encore-for-asset-management) to help with asset management. I've been testing encore a few days now and it's very easy and intuitive to use. So I propose to replace our current setup with gulp/assetic with encore. For our setup this would mean a encore config of +- 20 lines instead of gulp config of +- 60 lines.

Pro's:
- Encore is developed and supported by sensiolabs/symfony community
- We can remove assetic (compiled assets will be committed so no more assets building in production)
- With this change it will be easier to implement the new layout (easy compile, cleanup of the current css, etc)

\+ Currently there is a weird issue on the local machine if assets install has been run on the local machine instead of the vagrant box. The local absolute path to an image/font/... is used and this will not work on the vagrant box. This will also be solved with the default setup of encore.

Steps/Todo's:

- [x] Move the current gulp setup to the root of the project (no need to have it in the bundle) (#321)
- [x] Convert the current gulp setup to webpack encore + declare our frontend dependencies in the `package.json` instead of committing them directly to the repo (easier dependency management) (#321)
- [x] Add some docs on how to generate our assets with encore (#325) 
- [ ] Cleanup current sass/css/js

**Comment by acrobat** [comment]
This issue is done. The cleanup of our current javascript and css/scss code can be done next year or when a redesign is done!
